### ISSUE TITLE
[Custom Logo Build]: Redrix (I'm going to use NixOS)

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ChocolateLoverRaj/scripts#28]
### Firmware type

Alt FW

### Board Name

redrix

### Logo

![My Custom Coreboot Logo](https://github.com/ChocolateLoverRaj/scripts/assets/52586855/844ef682-6a4b-4b46-8440-fc8948b939a5)

### DISABLE_HECI1_AT_PRE_BOOT

None

### EDK2_FULL_SCREEN_SETUP

None

### EDK2_BOOT_MANAGER_ESCAPE

None

### EDK2_BOOT_TIMEOUT

1

**Comment by dawidulu97** [comment]
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ i think you need to update this D:

**Comment by ChocolateLoverRaj** [comment]
I'm no longer maintaining this. But if you're interested you can fork it.
