### ISSUE TITLE
[Custom Logo Build]: ChromeOS logo

### ISSUE THREAD

**Issue by crisutf** [ChocolateLoverRaj/scripts#6]
### Board Name

Blooguard

### Logo

![My Custom Coreboot Logo](https://github.com/ChocolateLoverRaj/scripts/assets/52586855/844ef682-6a4b-4b46-8440-fc8948b939a5)

**Comment by ChocolateLoverRaj** [comment]
Board name has to be lowercase. Maybe I should make the script do lowercase...

**Comment by ChocolateLoverRaj** [comment]
also @Maxcheto do u really want the logo to be my pineapple logo (it's ok if yes)?
