### ISSUE TITLE
[Custom Logo Build]: chromeOS

### ISSUE THREAD

**Issue by crisutf** [ChocolateLoverRaj/scripts#8]
### Board Name

Blooguard

### Logo

![My Custom Coreboot Logo](https://github.com/ChocolateLoverRaj/scripts/assets/52586855/844ef682-6a4b-4b46-8440-fc8948b939a5) 
![Chrome-OS-New-Boot-Screen-Feature](https://github.com/ChocolateLoverRaj/scripts/assets/143294409/71662d72-5a7e-4824-9d09-018dedeaeb9b)

**Comment by ChocolateLoverRaj** [comment]
@Maxcheto you must have exactly 1 logo, not 2
