### ISSUE TITLE
[Custom Logo Build]: test if svg works

### ISSUE THREAD

**Issue by CoolPenguin27** [ChocolateLoverRaj/scripts#9]
### Board Name

delbin

### Logo

![My Custom Coreboot Logo](https://github.com/ChocolateLoverRaj/scripts/assets/108895116/90dd422f-4222-4775-858a-7a3118debed1)

**Comment by ChocolateLoverRaj** [comment]
@CoolPenguin27 would this be the expected PNG form of the SVG image?
![test](https://github.com/ChocolateLoverRaj/scripts/assets/52586855/8c48f0ff-4f2c-4a05-bdf7-37ca370d75cf)
